// Dummy data for the placement system

export const STUDENTS = [
  {
    id: 'S001',
    name: 'Rahul Kumar',
    email: 'rahul@example.com',
    cgpa: 8.5,
    department: 'CSE',
    passingYear: 2024,
    resume: 'rahul_resume.pdf',
  },
  {
    id: 'S002',
    name: 'Priya Singh',
    email: 'priya@example.com',
    cgpa: 7.8,
    department: 'ECE',
    passingYear: 2024,
    resume: 'priya_resume.pdf',
  },
  {
    id: 'S003',
    name: 'Amit Patel',
    email: 'amit@example.com',
    cgpa: 9.2,
    department: 'CSE',
    passingYear: 2024,
    resume: 'amit_resume.pdf',
  },
];

export const COMPANIES = [
  {
    id: 'C001',
    name: 'TechCorp Solutions',
    email: 'hr@techcorp.com',
    requiredCGPA: 8.0,
    allowedDepartments: ['CSE', 'ECE'],
    year: 2024,
    ctc: 12,
  },
  {
    id: 'C002',
    name: 'DataSoft Industries',
    email: 'careers@datasoft.com',
    requiredCGPA: 7.5,
    allowedDepartments: ['CSE'],
    year: 2024,
    ctc: 10,
  },
  {
    id: 'C003',
    name: 'CloudDynamics',
    email: 'hiring@clouddynamics.com',
    requiredCGPA: 8.5,
    allowedDepartments: ['CSE', 'ECE', 'ME'],
    year: 2024,
    ctc: 15,
  },
];

export const JOBS = [
  {
    id: 'J001',
    companyId: 'C001',
    companyName: 'TechCorp Solutions',
    title: 'Software Engineer',
    description: 'Develop scalable web applications',
    requiredCGPA: 8.0,
    allowedDepartments: ['CSE', 'ECE'],
    year: 2024,
    ctc: 12,
    position: 5,
  },
  {
    id: 'J002',
    companyId: 'C002',
    companyName: 'DataSoft Industries',
    title: 'Data Analyst',
    description: 'Analyze and visualize business data',
    requiredCGPA: 7.5,
    allowedDepartments: ['CSE'],
    year: 2024,
    ctc: 10,
    position: 3,
  },
  {
    id: 'J003',
    companyId: 'C003',
    companyName: 'CloudDynamics',
    title: 'Cloud Architect',
    description: 'Design cloud infrastructure solutions',
    requiredCGPA: 8.5,
    allowedDepartments: ['CSE', 'ECE', 'ME'],
    year: 2024,
    ctc: 15,
    position: 2,
  },
];

export const APPLICATIONS = [
  {
    id: 'APP001',
    studentId: 'S001',
    studentName: 'Rahul Kumar',
    jobId: 'J001',
    companyId: 'C001',
    companyName: 'TechCorp Solutions',
    status: 'Shortlisted',
    appliedDate: '2024-01-10',
    resume: 'rahul_resume.pdf',
  },
  {
    id: 'APP002',
    studentId: 'S001',
    studentName: 'Rahul Kumar',
    jobId: 'J002',
    companyId: 'C002',
    companyName: 'DataSoft Industries',
    status: 'Rejected',
    appliedDate: '2024-01-12',
    resume: 'rahul_resume.pdf',
  },
  {
    id: 'APP003',
    studentId: 'S002',
    studentName: 'Priya Singh',
    jobId: 'J001',
    companyId: 'C001',
    companyName: 'TechCorp Solutions',
    status: 'Applied',
    appliedDate: '2024-01-11',
    resume: 'priya_resume.pdf',
  },
  {
    id: 'APP004',
    studentId: 'S003',
    studentName: 'Amit Patel',
    jobId: 'J001',
    companyId: 'C001',
    companyName: 'TechCorp Solutions',
    status: 'Selected',
    appliedDate: '2024-01-09',
    resume: 'amit_resume.pdf',
  },
  {
    id: 'APP005',
    studentId: 'S003',
    studentName: 'Amit Patel',
    jobId: 'J003',
    companyId: 'C003',
    companyName: 'CloudDynamics',
    status: 'Interview',
    appliedDate: '2024-01-13',
    resume: 'amit_resume.pdf',
  },
];

export const STATUS_TIMELINE = [
  { step: 1, label: 'Applied', status: 'Applied' },
  { step: 2, label: 'Under Review', status: 'Under Review' },
  { step: 3, label: 'Shortlisted', status: 'Shortlisted' },
  { step: 4, label: 'Interview', status: 'Interview' },
  { step: 5, label: 'Selected', status: 'Selected' },
];
